### ISSUE TITLE
DOESNT DO ANYTHING

### ISSUE THREAD

**Issue by ze-nite** [dotfighter/torshammer#5]
I write everything: 
cd desktop
cd torshammer
torshammer.py -t (ip) -r 256

and then just turns back to the initial screen
![sem titulo-1](https://user-images.githubusercontent.com/33848154/33045530-0c63ced8-ce45-11e7-9c22-f1b10fda3adc.png)

**Comment by acepilot123** [comment]
./torshammer.py -t ip -r 256
